project_id = "acafwsglzdgafhlqjuld"

[functions.withdraw]
verify_jwt = false

[functions.ai-refine-request]
verify_jwt = false

[functions.moderate-content]
verify_jwt = false

[functions.auto-release-funds]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.stripe-onboard-seller]
verify_jwt = false

[functions.stripe-account-status]
verify_jwt = false

[functions.stripe-create-checkout]
verify_jwt = false

[functions.stripe-checkout-webhook]
verify_jwt = false

[functions.stripe-transfer-funds]
verify_jwt = false

[functions.stripe-refund]
verify_jwt = false

[functions.admin-order-message]
verify_jwt = false

[functions.sitemap]
verify_jwt = false
