project_id = "fgpzlmomrzcpefqcstdn"

[functions.withdraw]
verify_jwt = false

[functions.ai-refine-request]
verify_jwt = false

[functions.moderate-content]
verify_jwt = false

[functions.paypal-create-order]
verify_jwt = false

[functions.paypal-capture-order]
verify_jwt = false
